[terminal.themes.seoul256]
"theme_default" = { fg = "#d0d0d0", bg = "#3a3a3a", attrs = "Default" }
"error_message" = { fg = "#d75f87", bg = "theme_default", attrs = "theme_default" }
"text.normal" = { fg = "Default", bg = "Default", attrs = "Default" }
"text.unfocused" = { fg = "Grey", bg = "theme_default", attrs = "Dim" }
"text.error" = { fg = "Red", bg = "theme_default", attrs = "theme_default" }
"text.highlight" = { fg = "Blue", bg = "theme_default", attrs = "Reverse" }
"email_header" = { fg = "DodgerBlue1", bg = "Default", attrs = "Default" }
"highlight" = { fg = "Grey35", bg = "#d0d0d0", attrs = "Bold" }
"status.bar" = { fg = "#d0d0d0", bg = "#4e4e4e", attrs = "theme_default" }
"status.command_bar" = { fg = "#2a2a2a", bg = "#87afaf", attrs = "theme_default" }
"status.history" = { fg = "DeepPink2", bg = "LightPink3", attrs = "theme_default" }
"status.history.hints" = { fg = "Black", bg = "status.command_bar", attrs = "theme_default" }
"status.notification" = { fg = "Plum1", bg = "Default", attrs = "theme_default" }
"tab.focused" = { fg = "theme_default", bg = "theme_default", attrs = "theme_default" }
"tab.unfocused" = { fg = "White", bg = "Grey", attrs = "theme_default" }
"tab.bar" = { fg = "theme_default", bg = "theme_default", attrs = "theme_default" }
"widgets.list.header" = { fg = "Black", bg = "White", attrs = "Bold" }
"widgets.form.label" = { fg = "theme_default", bg = "theme_default", attrs = "Bold" }
"widgets.form.field" = { fg = "theme_default", bg = "theme_default", attrs = "theme_default" }
"widgets.form.highlighted" = { fg = "theme_default", bg = "Grey58", attrs = "theme_default" }
"widgets.options.highlighted" = { fg = "theme_default", bg = "Grey", attrs = "theme_default" }
"mail.sidebar" = { fg = "theme_default", bg = "theme_default", attrs = "theme_default" }
"mail.sidebar_divider" = { fg = "theme_default", bg = "theme_default", attrs = "theme_default" }
"mail.sidebar_account_name" = { fg = "mail.sidebar", bg = "mail.sidebar", attrs = "Bold" }
"mail.sidebar_unread_count" = { fg = "Grey46", bg = "theme_default", attrs = "theme_default" }
"mail.sidebar_index" = { fg = "Grey46", bg = "theme_default", attrs = "theme_default" }
"mail.sidebar_highlighted" = { fg = "Grey7", bg = "White", attrs = "theme_default" }
"mail.sidebar_highlighted_unread_count" = { fg = "mail.sidebar_highlighted", bg = "mail.sidebar_highlighted", attrs = "theme_default" }
"mail.sidebar_highlighted_index" = { fg = "mail.sidebar_index", bg = "mail.sidebar_highlighted", attrs = "theme_default" }
"mail.sidebar_highlighted_account" = { fg = "White", bg = "#4e4e4e", attrs = "theme_default" }
"mail.sidebar_highlighted_account_name" = { fg = "mail.sidebar_highlighted_account", bg = "mail.sidebar_highlighted_account", attrs = "Bold" }
"mail.sidebar_highlighted_account_unread_count" = { fg = "mail.sidebar_unread_count", bg = "mail.sidebar_highlighted_account", attrs = "theme_default" }
"mail.sidebar_highlighted_account_index" = { fg = "mail.sidebar_index", bg = "mail.sidebar_highlighted_account", attrs = "theme_default" }
"mail.listing.compact.even" = { fg = "theme_default", bg = "Grey19", attrs = "theme_default" }
"mail.listing.compact.odd" = { fg = "theme_default", bg = "theme_default", attrs = "theme_default" }
"mail.listing.compact.even_unseen" = { fg = "Black", bg = "Grey78", attrs = "theme_default" }
"mail.listing.compact.odd_unseen" = { fg = "Black", bg = "Grey78", attrs = "theme_default" }
"mail.listing.compact.even_selected" = { fg = "theme_default", bg = "#85add4", attrs = "theme_default" }
"mail.listing.compact.odd_selected" = { fg = "theme_default", bg = "#85add4", attrs = "theme_default" }
"mail.listing.compact.even_highlighted" = { fg = "theme_default", bg = "Grey58", attrs = "theme_default" }
"mail.listing.compact.odd_highlighted" = { fg = "theme_default", bg = "Grey58", attrs = "theme_default" }
"mail.listing.conversations" = { fg = "Grey", bg = "theme_default", attrs = "theme_default" }
"mail.listing.conversations.subject" = { fg = "theme_default", bg = "theme_default", attrs = "theme_default" }
"mail.listing.conversations.from" = { fg = "Grey", bg = "theme_default", attrs = "theme_default" }
"mail.listing.conversations.date" = { fg = "#d68787", bg = "theme_default", attrs = "theme_default" }
"mail.listing.conversations.unseen" = { fg = "Black", bg = "Grey78", attrs = "theme_default" }
"mail.listing.conversations.highlighted" = { fg = "theme_default", bg = "Grey58", attrs = "Bold" }
"mail.listing.conversations.selected" = { fg = "theme_default", bg = "#85add4", attrs = "theme_default" }
"mail.listing.plain.even" = { fg = "theme_default", bg = "Grey19", attrs = "theme_default" }
"mail.listing.plain.odd" = { fg = "theme_default", bg = "theme_default", attrs = "theme_default" }
"mail.listing.plain.even_unseen" = { fg = "Black", bg = "Grey78", attrs = "theme_default" }
"mail.listing.plain.odd_unseen" = { fg = "Black", bg = "Grey78", attrs = "theme_default" }
"mail.listing.plain.even_selected" = { fg = "theme_default", bg = "#85add4", attrs = "theme_default" }
"mail.listing.plain.odd_selected" = { fg = "theme_default", bg = "#85add4", attrs = "theme_default" }
"mail.listing.plain.even_highlighted" = { fg = "theme_default", bg = "Grey58", attrs = "theme_default" }
"mail.listing.plain.odd_highlighted" = { fg = "theme_default", bg = "Grey58", attrs = "theme_default" }
"mail.view.headers" = { fg = "#85add4", bg = "theme_default", attrs = "theme_default" }
"mail.view.headers_names" = { fg = "mail.view.headers", bg = "mail.view.headers", attrs = "mail.view.headers" }
"mail.view.headers_area" = { fg = "theme_default", bg = "theme_default", attrs = "theme_default" }
"mail.view.body" = { fg = "theme_default", bg = "theme_default", attrs = "theme_default" }
"mail.view.thread.indentation.a" = { fg = "theme_default", bg = "#d68787", attrs = "theme_default" }
"mail.view.thread.indentation.b" = { fg = "theme_default", bg = "#5f865f", attrs = "theme_default" }
"mail.view.thread.indentation.c" = { fg = "theme_default", bg = "#d8af5f", attrs = "theme_default" }
"mail.view.thread.indentation.d" = { fg = "theme_default", bg = "#85add4", attrs = "theme_default" }
"mail.view.thread.indentation.e" = { fg = "theme_default", bg = "#d7afaf", attrs = "theme_default" }
"mail.view.thread.indentation.f" = { fg = "theme_default", bg = "#87afaf", attrs = "theme_default" }
"mail.listing.attachment_flag" = { fg = "LightSlateGrey", bg = "theme_default", attrs = "theme_default" }
"mail.listing.thread_snooze_flag" = { fg = "Red", bg = "theme_default", attrs = "theme_default" }
"mail.listing.tag_default" = { fg = "White", bg = "Grey", attrs = "Bold" }
"pager.highlight_search" = { fg = "White", bg = "Teal", attrs = "Bold" }
"pager.highlight_search_current" = { fg = "White", bg = "NavyBlue", attrs = "Bold" }

